### ISSUE TITLE
Write rules and articles for Beer app

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/beer-o-meter#1]

**Comment by akaSun4e** [comment]
### Правила
**соло**
Определитесь с дистанцией для проведения забега и убедитесь, что она безопасна!

1. Наполните бокал пивом.
2. Когда будете готовы бежать/идти, нажмите START и начните движение.
3. Старайтесь пролить как можно меньше пива, преодолев  дистанцию как можно быстрее.
4. Достигнув конца дистанции, нажмите FINISH. 

Чем меньше пива пролито, тем лучше Ваши баланс и координация. Улучшайте свои показатели! Берегите пиво!

Determine the distance for the race and make sure it is safe!

1. Fill the mug with beer
2. When you are ready to run/walk, press START and start moving.
3. Try to spill as little beer as possible, moving as quickly as you can.
4. When you reach the end of the distance, press FINISH 

The lesser beer is spilled, the better your balance and coordination is. Improve your performance! Save your beer!

**дуэль**
Убедитесь, что на устройстве Вашего соперника установлена программа Beer-o-Meter. При необходимости покажите QR код для удобной установки.
QR Google Play & App Store
Определитесь с дистанцией для проведения забега и убедитесь, что она безопасна!

1. Наполните бокалы пивом.
2. Когда будете готовы бежать/идти нажмите START. одновременно и начните движение по сигналу GO!
3. Старайтесь пролить как можно меньше пива преодолев  дистанцию как можно быстрее.
4. Достигнув конца дистанции нажмите FINISH.
5. Победитель гонки получает +10 к показателю процента сохранённого пива в бокале. 

Чем меньше пива пролито тем лучше Ваши баланс и координация. Улучшайте свои показатели! Сохраните больше пива чем Ваш соперник!

Make sure your opponent has Beer-o-Meter installed. If needed, show QR code for convenient installation.
QR Google Play & App Store
Determine the distance for the race and make sure it is safe!

1. Fill mugs with beer
2. When you are ready to run/walk, press START simultaneously and start moving on the GO signal.
3. Try to spill as little beer as possible, moving as quickly as you can.
4. When you reach the end of the distance, press FINISH 
5. Winner of the race gets +10 to percent of the beer saved in the mug

The lesser beer is spilled, the better your balance and coordination is. Improve your performance! Save more beer than your opponent!
