### ISSUE TITLE
Add in desing "Beer tap"

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/beer-o-meter#2]

**Comment by MariaMyalik** [comment]
![Image](https://user-images.githubusercontent.com/96649047/170259698-eeb43bbe-9263-4d5d-8805-fd87eb74ba71.png)

**Comment by MariaMyalik** [comment]
https://www.figma.com/file/kfV66bWsQAJ8sbPMfDAQil/HealthYouUp_Game?node-id=1199%3A19975
